/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbm;

import javax.swing.JFrame;

/**
 *
 * @author Hp
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnRegisterNewStudent = new javax.swing.JButton();
        btnSearchDetails = new javax.swing.JButton();
        btnMakeAdmin = new javax.swing.JButton();
        btnSearchDetails1 = new javax.swing.JButton();
        btnSubjectSelection = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnRegisterNewStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegisterNewStudent.setText("Register New Student");
        btnRegisterNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterNewStudentActionPerformed(evt);
            }
        });

        btnSearchDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchDetails.setText("Search Details");
        btnSearchDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDetailsActionPerformed(evt);
            }
        });

        btnMakeAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMakeAdmin.setText("Make Admin");
        btnMakeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeAdminActionPerformed(evt);
            }
        });

        btnSearchDetails1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchDetails1.setText("Courses");
        btnSearchDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDetails1ActionPerformed(evt);
            }
        });

        btnSubjectSelection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubjectSelection.setText("Subject Selection");
        btnSubjectSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectSelectionActionPerformed(evt);
            }
        });

        btnPayments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPayments.setText("Payments");
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(btnMakeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubjectSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRegisterNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegisterNewStudent)
                .addGap(18, 18, 18)
                .addComponent(btnSearchDetails)
                .addGap(18, 18, 18)
                .addComponent(btnSearchDetails1)
                .addGap(18, 18, 18)
                .addComponent(btnSubjectSelection)
                .addGap(18, 18, 18)
                .addComponent(btnPayments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnMakeAdmin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterNewStudentActionPerformed
        Register rgr = new Reister();
        rgr.setVisible(true);
        rgr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnRegisterNewStudentActionPerformed

    private void btnMakeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeAdminActionPerformed
        MakeAdmin mad = new MakeAdmin();
        mad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMakeAdminActionPerformed

    private void btnSearchDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDetails1ActionPerformed
        Courses cur = new Courses();
        cur.setVisible(true);
    }//GEN-LAST:event_btnSearchDetails1ActionPerformed

    private void btnSubjectSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectSelectionActionPerformed
        SubjectSlection ss = new SubjectSlection();
        ss.setVisible(true);
    }//GEN-LAST:event_btnSubjectSelectionActionPerformed

    private void btnSearchDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchDetailsActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        Payments pymnts = new Payments();
        pymnts.setVisible(true);
        pymnts.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnPaymentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeAdmin;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnRegisterNewStudent;
    private javax.swing.JButton btnSearchDetails;
    private javax.swing.JButton btnSearchDetails1;
    private javax.swing.JButton btnSubjectSelection;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class Reister extends Register {

        public Reister() {
        }
    }
}
